# Generated by Django 4.2.20 on 2025-03-26 18:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
        ('castle_graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castle_name', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField()),
                ('neighbors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.castle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('question_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CaptureCastle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.IntegerField(choices=[(0, 'Solved'), (1, 'Conquered')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.castle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestgroup')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='castle_graph.submission')),
            ],
        ),
    ]
