# Generated by Django 4.2.20 on 2025-03-28 16:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
        ('castle_graph', '0002_castle_submission_submissionitem_capturecastle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('judge0_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='capturecastle',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='castle',
            name='identifier',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestgroup',
            name='lead_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestuser'),
        ),
        migrations.AddField(
            model_name='contestuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestuser',
            name='payment_identifier',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_code',
            field=models.FileField(default=1, upload_to='submissions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='castle',
            name='neighbors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='castle',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
        migrations.AlterField(
            model_name='contestuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestgroup'),
        ),
        migrations.AlterField(
            model_name='contestuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestuser'),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='result',
            field=models.IntegerField(choices=[(1, 'In Queue'), (2, 'Processing'), (3, 'Accepted'), (4, 'Wrong Answer'), (5, 'Time Limit Exceeded'), (6, 'Compilation Error'), (7, 'Runtime Error (SIGSEGV)'), (8, 'Runtime Error (SIGXFSZ)'), (9, 'Runtime Error (SIGFPE)'), (10, 'Runtime Error (SIGABRT)'), (11, 'Runtime Error (NZEC)'), (12, 'Runtime Error (Other)'), (13, 'Internal Error'), (14, 'Exec Format Error'), (15, 'Unknown Error')], default=1),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionitem',
            name='token',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_code', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestuser')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'rejected'), (2, 'accepted')], default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestgroup')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castle_graph.contestuser')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='castle_graph.submissionlanguage'),
            preserve_default=False,
        ),
    ]
