# Generated by Django 4.2.20 on 2025-03-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_identifier',
        ),
    ]
